import type { InterviewQuestion } from "./types";

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  // Block A: General Company Info (5 questions)
  {
    id: "a1",
    block: "A",
    blockName: "Общая информация о компании",
    question: "Какова основная сфера деятельности вашей компании?",
    required: true,
    expressMode: true,
    order: 1,
  },
  {
    id: "a2",
    block: "A",
    blockName: "Общая информация о компании",
    question: "Какова организационная структура компании (основные отделы и подразделения)?",
    required: true,
    expressMode: false,
    order: 2,
  },
  {
    id: "a3",
    block: "A",
    blockName: "Общая информация о компании",
    question: "Какие ключевые продукты или услуги вы предоставляете?",
    required: true,
    expressMode: true,
    order: 3,
  },
  {
    id: "a4",
    block: "A",
    blockName: "Общая информация о компании",
    question: "Сколько сотрудников работает в компании?",
    required: false,
    expressMode: false,
    order: 4,
  },
  {
    id: "a5",
    block: "A",
    blockName: "Общая информация о компании",
    question: "Какие основные рынки и целевые аудитории обслуживает компания?",
    required: false,
    expressMode: false,
    order: 5,
  },

  // Block B: Process Description (8 questions)
  {
    id: "b1",
    block: "B",
    blockName: "Описание процесса",
    question: "Какой бизнес-процесс вы хотите описать? Дайте ему название.",
    required: true,
    expressMode: true,
    order: 6,
  },
  {
    id: "b2",
    block: "B",
    blockName: "Описание процесса",
    question: "Какова основная цель этого процесса?",
    required: true,
    expressMode: true,
    order: 7,
  },
  {
    id: "b3",
    block: "B",
    blockName: "Описание процесса",
    question: "Кто является владельцем (ответственным) процесса?",
    required: true,
    expressMode: true,
    order: 8,
  },
  {
    id: "b4",
    block: "B",
    blockName: "Описание процесса",
    question: "Какие роли (должности) участвуют в процессе?",
    required: true,
    expressMode: true,
    order: 9,
  },
  {
    id: "b5",
    block: "B",
    blockName: "Описание процесса",
    question: "Что запускает (триггер) начало процесса?",
    required: true,
    expressMode: true,
    order: 10,
  },
  {
    id: "b6",
    block: "B",
    blockName: "Описание процесса",
    question: "Каков ожидаемый результат (выход) процесса?",
    required: true,
    expressMode: true,
    order: 11,
  },
  {
    id: "b7",
    block: "B",
    blockName: "Описание процесса",
    question: "Какие внешние участники (клиенты, поставщики) взаимодействуют с процессом?",
    required: false,
    expressMode: false,
    order: 12,
  },
  {
    id: "b8",
    block: "B",
    blockName: "Описание процесса",
    question: "Как часто выполняется этот процесс (раз в день, неделю, месяц)?",
    required: false,
    expressMode: false,
    order: 13,
  },

  // Block C: Steps and Actions (10 questions)
  {
    id: "c1",
    block: "C",
    blockName: "Этапы и действия",
    question: "Опишите основные этапы (крупные стадии) процесса от начала до конца.",
    required: true,
    expressMode: true,
    order: 14,
  },
  {
    id: "c2",
    block: "C",
    blockName: "Этапы и действия",
    question: "Какие конкретные действия выполняются на каждом этапе?",
    required: true,
    expressMode: true,
    order: 15,
  },
  {
    id: "c3",
    block: "C",
    blockName: "Этапы и действия",
    question: "Кто ответственный за выполнение каждого действия?",
    required: true,
    expressMode: false,
    order: 16,
  },
  {
    id: "c4",
    block: "C",
    blockName: "Этапы и действия",
    question: "Сколько времени обычно занимает каждый этап?",
    required: false,
    expressMode: false,
    order: 17,
  },
  {
    id: "c5",
    block: "C",
    blockName: "Этапы и действия",
    question: "Есть ли в процессе точки принятия решений? Если да, опишите условия и варианты.",
    required: true,
    expressMode: false,
    order: 18,
  },
  {
    id: "c6",
    block: "C",
    blockName: "Этапы и действия",
    question: "Есть ли действия, которые могут выполняться параллельно?",
    required: false,
    expressMode: false,
    order: 19,
  },
  {
    id: "c7",
    block: "C",
    blockName: "Этапы и действия",
    question: "Какие документы создаются или используются на каждом этапе?",
    required: false,
    expressMode: false,
    order: 20,
  },
  {
    id: "c8",
    block: "C",
    blockName: "Этапы и действия",
    question: "Какие согласования или утверждения требуются в процессе?",
    required: false,
    expressMode: false,
    order: 21,
  },
  {
    id: "c9",
    block: "C",
    blockName: "Этапы и действия",
    question: "Что происходит при возникновении ошибки или отклонения от нормального хода?",
    required: false,
    expressMode: false,
    order: 22,
  },
  {
    id: "c10",
    block: "C",
    blockName: "Этапы и действия",
    question: "Какие промежуточные результаты (продукты) создаются в ходе процесса?",
    required: false,
    expressMode: false,
    order: 23,
  },

  // Block D: Information Systems (6 questions)
  {
    id: "d1",
    block: "D",
    blockName: "Информационные системы",
    question: "Какие информационные системы используются в процессе (CRM, ERP, 1С и т.д.)?",
    required: false,
    expressMode: false,
    order: 24,
  },
  {
    id: "d2",
    block: "D",
    blockName: "Информационные системы",
    question: "Какие системы интегрированы между собой?",
    required: false,
    expressMode: false,
    order: 25,
  },
  {
    id: "d3",
    block: "D",
    blockName: "Информационные системы",
    question: "Какие данные передаются между системами?",
    required: false,
    expressMode: false,
    order: 26,
  },
  {
    id: "d4",
    block: "D",
    blockName: "Информационные системы",
    question: "Используются ли электронные таблицы (Excel, Google Sheets) в процессе? Для чего?",
    required: false,
    expressMode: false,
    order: 27,
  },
  {
    id: "d5",
    block: "D",
    blockName: "Информационные системы",
    question: "Какие каналы коммуникации используются (email, мессенджеры, телефон)?",
    required: false,
    expressMode: false,
    order: 28,
  },
  {
    id: "d6",
    block: "D",
    blockName: "Информационные системы",
    question: "Есть ли ручные операции, которые могли бы быть автоматизированы?",
    required: false,
    expressMode: false,
    order: 29,
  },

  // Block E: Metrics and KPI (5 questions)
  {
    id: "e1",
    block: "E",
    blockName: "Метрики и KPI",
    question: "Какие ключевые показатели эффективности (KPI) используются для оценки процесса?",
    required: false,
    expressMode: false,
    order: 30,
  },
  {
    id: "e2",
    block: "E",
    blockName: "Метрики и KPI",
    question: "Каковы целевые значения этих показателей?",
    required: false,
    expressMode: false,
    order: 31,
  },
  {
    id: "e3",
    block: "E",
    blockName: "Метрики и KPI",
    question: "Как часто измеряются эти показатели?",
    required: false,
    expressMode: false,
    order: 32,
  },
  {
    id: "e4",
    block: "E",
    blockName: "Метрики и KPI",
    question: "Кто отвечает за мониторинг показателей?",
    required: false,
    expressMode: false,
    order: 33,
  },
  {
    id: "e5",
    block: "E",
    blockName: "Метрики и KPI",
    question: "Какие действия предпринимаются при отклонении от целевых значений?",
    required: false,
    expressMode: false,
    order: 34,
  },

  // Block F: Problems and Bottlenecks (8 questions)
  {
    id: "f1",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Какие основные проблемы существуют в текущем процессе?",
    required: false,
    expressMode: false,
    order: 35,
  },
  {
    id: "f2",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "На каких этапах чаще всего возникают задержки?",
    required: false,
    expressMode: false,
    order: 36,
  },
  {
    id: "f3",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Есть ли дублирование работы между сотрудниками или отделами?",
    required: false,
    expressMode: false,
    order: 37,
  },
  {
    id: "f4",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Какие этапы требуют наибольших трудозатрат?",
    required: false,
    expressMode: false,
    order: 38,
  },
  {
    id: "f5",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Бывают ли ситуации потери информации при передаче между участниками?",
    required: false,
    expressMode: false,
    order: 39,
  },
  {
    id: "f6",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Какой процент выполнений процесса завершается с ошибками?",
    required: false,
    expressMode: false,
    order: 40,
  },
  {
    id: "f7",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Какие жалобы поступают от клиентов или внутренних заказчиков?",
    required: false,
    expressMode: false,
    order: 41,
  },
  {
    id: "f8",
    block: "F",
    blockName: "Проблемы и узкие места",
    question: "Какие ресурсы (люди, системы, бюджет) являются узким местом?",
    required: false,
    expressMode: false,
    order: 42,
  },

  // Block G: Optimization Requirements (8 questions)
  {
    id: "g1",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Какие улучшения процесса вы считаете наиболее приоритетными?",
    required: false,
    expressMode: false,
    order: 43,
  },
  {
    id: "g2",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Какие этапы вы хотели бы автоматизировать в первую очередь?",
    required: false,
    expressMode: false,
    order: 44,
  },
  {
    id: "g3",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Рассматриваете ли вы внедрение новых информационных систем?",
    required: false,
    expressMode: false,
    order: 45,
  },
  {
    id: "g4",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Какой бюджет готовы выделить на оптимизацию процесса?",
    required: false,
    expressMode: false,
    order: 46,
  },
  {
    id: "g5",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Какие ограничения необходимо учитывать при изменении процесса?",
    required: false,
    expressMode: false,
    order: 47,
  },
  {
    id: "g6",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Готовы ли вы к изменению организационной структуры для оптимизации?",
    required: false,
    expressMode: false,
    order: 48,
  },
  {
    id: "g7",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Какие инструменты ИИ (чат-боты, автоматизация, аналитика) были бы полезны?",
    required: false,
    expressMode: false,
    order: 49,
  },
  {
    id: "g8",
    block: "G",
    blockName: "Требования к оптимизации",
    question: "Каковы ожидаемые сроки внедрения изменений?",
    required: false,
    expressMode: false,
    order: 50,
  },
];

export function getQuestionsByMode(mode: "full" | "express"): InterviewQuestion[] {
  if (mode === "express") {
    return INTERVIEW_QUESTIONS.filter((q) => q.expressMode);
  }
  return INTERVIEW_QUESTIONS;
}

export function getQuestionsByBlock(block: string): InterviewQuestion[] {
  return INTERVIEW_QUESTIONS.filter((q) => q.block === block);
}
